# Generated by Django 3.0.8 on 2020-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0003_auto_20200723_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountedprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
