# Generated by Django 3.0.8 on 2020-07-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0004_auto_20200723_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=' static/img/product/product-4.jpg', upload_to='products/'),
        ),
    ]
