# Generated by Django 3.0.8 on 2020-07-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0006_auto_20200724_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
