# Generated by Django 3.0.8 on 2020-07-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0008_auto_20200726_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=' static/img/1503549.jpg', upload_to='static/img/'),
        ),
    ]
