# Generated by Django 3.0.8 on 2020-07-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0013_auto_20200726_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='1503549.jpg', upload_to='product/'),
        ),
    ]
